# Generated by Django 4.2 on 2026-04-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0003_todoitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
    ]
